#!/bin/sh

# Test for required programs
if test dpkg; then
  DPKG=dpkg
else
  echo "Make sure you have dpkg installed and in your path before running $0"
  exit
fi
if test awk; then
  AWK=awk
else
  echo "Make sure you have awk installed and in your path before running $0"   
  exit
fi

# Check to make sure all arguments are there
if test $# -ne 2; then
  echo "Usage: $0 [basepath] [lib[version]]"
  echo "  ie: $0 /sw readline.4.3"
  exit
fi

# Initialize varables
BASEPATH=$1
LIB=$2

VERBOSE="false"

# Start Program
echo searching for stuff linked against $LIB in $BASEPATH/bin and $BASEPATH/lib...

# Check in BASEPATH/bin
for i in `ls -1d $BASEPATH/bin/*`; do
  if test "`otool -L $i | grep $LIB`" != ""; then
    PKG=`$DPKG -S $i | $AWK {'print $1'}`
    echo "Found in $PKG ($i)"
    if $VERBOSE = "true"; then
      otool -L $i
    fi
  fi
done

# check in BASEPATH/lib
for i in `ls -1d $BASEPATH/lib/*`; do
  if test "`otool -L $i | grep $LIB`" != ""; then
    PKG=`$DPKG -S $i | $AWK {'print $1'}`
    echo "Found in $PKG ($i)"
    if $VERBOSE = "true"; then
      otool -L $i
    fi
  fi
done
for i in `ls -1d $BASEPATH/lib/*/ $BASEPATH/lib/*/*/ $BASEPATH/lib/*/*/*/ $BASEPATH/lib/*/*/*/*/`; do
  for j in $i*.*; do
    if test "`otool -L $j | grep $LIB`" != ""; then
      PKG=`$DPKG -S $j | $AWK {'print $1'}`
      echo "Found in $PKG ($j)"
      if $VERBOSE = "true"; then
        otool -L $j
      fi
    fi
  done
done
