#!/usr/bin/perl

use strict;

system("fink selfupdate-cvs > /tmp/.finkupdate 2>&1");
my @list = `cat /tmp/.finkupdate`;
my $datadir = $ENV{BDDATA}."/";
my $dist;

if (exists $ENV{CURREL} and defined $ENV{CURREL}) {
  $dist = $ENV{CURREL};
} else {
  chomp($dist = `cat $ENV{BDDATA}/current`);
}

my ($modified, $removed, $added) = (0, 0, 0);
my ($a, $m, $r) = (0, 0, 0);
my (@adding, @modified, @removing);
my ($line, $j, $junk, @junk, $file, $content);

foreach $line (@list) {
  chomp($line);
  if ($line =~ /^(M|P|U|R|C|\?|A).*\/(unstable|stable)\/.*\/(.*)-(.*-.*)\..*$/) {
    my $action = $1;
    my $pdist = $2;
    my $package = $3;
    my $version = $4;
    if ($pdist eq $dist) {
      if ($action eq "P") {
        $modified++;
        push @modified, $package;
      } elsif ($action eq "U") {
        $added++;
        push @adding, $package;
      } else {
        $junk++;
        push @junk, $line;
      }
    } else {
      $junk++;
      push @junk, $line;
    }
  } elsif ($line =~ /^cvs\ server\:\ (.*)\ is\ no\ longer\ in\ the\ repository$/) {
    if ($1 =~ /^.*\/(unstable|stable)\/.*\/(.*)-(.*-.*)\..*$/) {
      if ($1 eq $dist) {
        $removed++;
        push @removing, $2;
      }
   }
  } else {
    $junk++;
    push @junk, $line;
  }
}

$m = join(" ,", @modified);
$a = join(" ,", @adding);
$r = join(" ,", @removing);

print "\n";
print "During the update there was $junk junk lines.\n";
print "\n";
print "CVS update found your $dist bindist needs the following:\n";
print "Packages: $added Added, $modified Rebuilt and $removed Removed\n";
print "\n";
if ($added > 0) {
  $file = $datadir.$dist."-add.list";
  $content = join(" \n", @adding);

  print "Adding: $a\n";
  print "Writing files...";
  open(IN,">$file") or die "can't open $file: $!";
    print IN $content;
  close(IN);
  print "done.\n";
  print "\n";
}
if ($modified > 0) {
  $file = $datadir.$dist."-rebuild.list";
  $content = join(" \n", @modified);      

  print "Rebuilding: $m\n";
  print "Writing files...";
  open(IN,">$file") or die "can't open $file: $!";
    print IN $content; 
  close(IN);   
  print "done.\n";
  print "\n";
}
if ($removed > 0) {
  $file = $datadir.$dist."-remove.list";
  $content = join(" \n", @removing);      

  print "Removing: $r\n";
  print "Writing files...";
  open(IN,">$file") or die "can't open $file: $!";
    print IN $content; 
  close(IN);   
  print "done.\n";
  print "\n";
}

if ($junk > 0) {
  $file = $datadir."junk.list";
  $content = join(" \n", @junk);      

  print "Loging junk lines to $file.\n";
  open(IN,">$file") or die "can't open $file: $!";
    print IN $content; 
  close(IN);
}

print "\n";
print "Done.\n";

exit 0;
