#!/usr/bin/perl
use strict;
use warnings;

$| = 1;

my ($mirrorfile) = @ARGV;

unless ( length $mirrorfile ) {
	print "Need location for rsync mirror file.\n";
	exit(1);
}

open my $fh, '<', $mirrorfile or die $!;
	while (<$fh>) {
		chomp;
		next if "";
		next if m/^[\s|\t]*#/;

		if (m/^[\s|\t]*(.+):[\s|\t]+rsync:\/\/([a-zA-Z0-9\.]+)\/(.*)\/$/) {
			print "$1 ";
			system("./check-finkrsync -H $2 -p $3");
		}
	}
close $fh or die $!;
