#!/usr/bin/perl

$| = 1;

use strict;
use warnings;

my ($maint, $progname, $pkgreg, $finkline, @pkglist, $pkg);
my ($bin, $man);
my $fink = "fink list";
my $defaults = "-i -w 200";

# Set name of current program
($progname = $0) =~ s#.*/##;

if (!$ARGV[0] || $ARGV[2]) {
  print "Usage: $progname [maint] <package regex>\n";
  print "   ie: $progname thesin pm581\n";
  exit(1);
} else {
  if ($ARGV[1]) {
    $maint = "-m $ARGV[0]";
    $pkgreg = $ARGV[1];
  } else {
    $maint = "";
    $pkgreg = $ARGV[0];
  }
}

$finkline = "$fink $defaults $maint $pkgreg";

if (open(FINK, "$finkline |")) {
  while (<FINK>) {
    chomp();
    if (/^\s*\(?i\)?\s*(\S+)\s+.*$/) {
      push(@pkglist, $1);
    }
  }
  close(FINK);
} else {
  print "ERROR: couldn't get list from '$fink'!\n";
  exit(1);
}

foreach $pkg (@pkglist) {
  $bin = 0;
  $man = 0;
  if (open(DPKG, "dpkg -L $pkg |")) {
    while (<DPKG>) {
      chomp();
      if (/\/bin\//) {
        $bin = 1;
      } elsif (/\/man\//) {
        $man = 1;
      }
    }
    close(DPKG);
    if ($man or $bin) {
      print "$pkg needs a ";
      print "'-man'" if $man;
      print " and " if $man and $bin;
      print "'-bin'" if $bin;
      print " split.\n";
    } else {
      print "$pkg is OK.\n";
    }
  } else {
    print "ERROR: couldn't run 'dpkg -L' on '$pkg'!\n";
    next;
  }
}
