#!/usr/bin/perl

$| = 1;

use strict;
use warnings;

my ($dir, $progname, $symbols);

# Set name of current program
($progname = $0) =~ s#.*/##;

unless ($ARGV[0] && $ARGV[1]) {
  print "Usage: $progname <dir> <symbols>\n";
  print "   ie: $progname /usr/lib \'_des_ede3_cbc_encrypt|_des_set_odd_parity\'\n";
  exit(1);
} else {
  $dir = $ARGV[0];
  $symbols = $ARGV[1];
}

my $grepcmd = "grep -Er '$symbols' $dir";
my $nmcmd = "nm";
my $grepnmcmd = "grep -E '$symbols'";
my $dpkgcmd = "dpkg -S";

my (@matches, $match, @output, $line, $deb);

print "Searching <$dir> for <\'$symbols\'>...\n\n";

@matches = `$grepcmd`;

foreach $match (@matches) {
  if ($match =~ /Binary file (.+) matches/i) {
    $match = $1;
  }
  $deb = `$dpkgcmd $match`;
  if ($deb =~ /^(.+): .*$/i) {
    $deb = $1;
  }
  print "$match ($deb):\n";
  @output = `$nmcmd $match | $grepnmcmd`;
  foreach $line (@output) {
    chomp($line);
    if ($line) {
      print "\t$line\n";
    }
  }
  print "\n";
}

exit(0);
