#!/bin/sh

# Check to make sure all arguments are there
if test $# -lt 1; then
  echo ""
  echo "::: Usage: $0 [-b] file"
  echo ""
  echo "      -b   creats a .mac file first (backup of the mac formated file)"
  echo ""
  echo "      ie: $0 somedumbmac^Mfile.txt"
  echo ""
  exit
fi

# set file the fix and check options
echo ""
if [ $1 = "-b" ]; then
  FILE=$2
  echo "::: Making backup  ($FILE.mac)"
  # make backup of file as requested
  cp $FILE $FILE.mac
else
  FILE=$1
fi

echo "::: Reformating $FILE to unix format"
# run reformat and replace file
perl -pi -e 's,\r,\n,gs' $FILE
echo "::: Done"
echo ""
exit
